# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "0w1qc5k9prxlfa9vry8m7kskq1fqpihwshqfq6haawf0k0mj5zjs";
    x86_64-linux = "0wwadrj16i593ix6ydiv49ipbfvj7svia4844pp3nk2hpwvygbm2";
    aarch64-linux = "09m509bbz852kyj14iisbp4v3vf1vir3ycn347zpxzzd1dkbhnkj";
    x86_64-darwin = "04p8s13lhhy462iy3vgbiwhyilqr2ng5w8alrbi17z72366yxc6g";
    aarch64-darwin = "1km52dpvjwr34jc033iawh6k88x7alll5kfsx91n9xipz2s4d272";
  };

  urlMap = {
    i686-linux = "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Linux_aarch64.tar.gz";
    x86_64-darwin = "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "reward";
  version = "0.7.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./reward $out/bin/reward
  '';
  postInstall = ''
    installShellCompletion ./completions/reward/*
  '';

  system = system;

  meta = {
    description = "Reward is CLI utility for orchestrating Docker based development environments.";
    homepage = "https://github.com/rewardenv/reward";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
