# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "1vmrj4d3y9ahl6gjp72ldh0m0r3kvxwr91w44pzw85jff2w24yri";
    x86_64-linux = "0d5blqhrbfv81cish38jvs94bjx83v2ficsxaj390f8z4c9n309v";
    aarch64-linux = "177ab9kn6rwdwi4caadwkcsqk7vipm4g2qsns3yh71b4n05m9vs3";
    x86_64-darwin = "19k32m224n0xkay80408rwsp08nawrsl926ybswpi81rb091pv73";
    aarch64-darwin = "1fx2j59knmqh4z4zlya1ry7y25sfbg5grdws1c7p428g0nc03862";
  };

  urlMap = {
    i686-linux = "https://github.com/rewardenv/reward/releases/download/v0.7.11/reward_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/rewardenv/reward/releases/download/v0.7.11/reward_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/rewardenv/reward/releases/download/v0.7.11/reward_Linux_aarch64.tar.gz";
    x86_64-darwin = "https://github.com/rewardenv/reward/releases/download/v0.7.11/reward_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/rewardenv/reward/releases/download/v0.7.11/reward_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "reward";
  version = "0.7.11";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./reward $out/bin/reward
  '';
  postInstall = ''
    installShellCompletion ./completions/reward/*
  '';

  meta = {
    description = "Reward is CLI utility for orchestrating Docker based development environments.";
    homepage = "https://github.com/rewardenv/reward";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
